### ISSUE TITLE
What are the differences between ldb and acme?

### ISSUE THREAD

**Issue by hooke007** [Artoriuz/luma-downscaler#2]
https://github.com/Artoriuz/luma-downscaler/blob/main/luma-downscaler-bilinear.glsl
https://gist.github.com/bjin/15f307e7a1bdb55842bbb663ee1950ed

**Comment by Artoriuz** [comment]
At 0.5x they should do the same thing, but one of them is hardcoded to always scale by 0.5x and the other isn't.

**Comment by hooke007** [comment]
> I was told that it was useless for performance.
https://github.com/mpv-player/mpv/issues/10564#issuecomment-1222428075

Any ideas?
